/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StudyProgramICS4U;

import java.util.ArrayList;

/**
 *
 * @author repan6047
 */
public class NotesMenu extends javax.swing.JFrame {
    //reference to the main menu
    MainMenu mainWindow;
    QuizMenu quizWindow;
    //index of arraylist
    int index = 0;
    //the arraylist
    ArrayList nList;
    /**
     * Creates new form NotesMenu
     */
    public NotesMenu(MainMenu m) {
        this.setTitle("Notes");
        initComponents();
        //opens the connection
        mainWindow = m;
        //gets the notes list
        nList = m.getNotes();
        //sets the text
        txtNotes.setText("" + nList.get(index));
        //sets the position
        txtNotes.setCaretPosition(0);
        //make the buttons visible
        btnNext.setVisible(true);
        btnPrev.setVisible(true);
    }
    
    public NotesMenu(QuizMenu q, MainMenu m){
        this.setTitle("Results");
        initComponents();
        quizWindow = q;
        mainWindow = m;
        //hide the buttons
        btnNext.setVisible(false);
        btnPrev.setVisible(false);
        //set the text and position
        txtNotes.setText(q.getResults());
        txtNotes.setCaretPosition(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtNotes = new javax.swing.JTextArea();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Notes");
        setResizable(false);

        txtNotes.setEditable(false);
        txtNotes.setColumns(20);
        txtNotes.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNotes.setLineWrap(true);
        txtNotes.setRows(5);
        txtNotes.setText("Waterfall Method:\n\n~~~~~~~~~\n\n~~~~~~~~~~~~~~~~\n\n~~\n\n~~~~~~~~~~~");
        txtNotes.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtNotes);

        btnPrev.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnPrev.setText("Prev");
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnMenu.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNext, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrev)
                    .addComponent(btnNext))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMenu)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        if(txtNotes.getText().substring(0, 4).equals("RESU")){
            quizWindow.dispose();
            mainWindow.setVisible(true);
            this.dispose();
        }else{
           //makes this windo visible
            mainWindow.setVisible(true);
            //hides the main menu
            this.setVisible(false); 
        }
        
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if(index == nList.size() - 1){//if at the end
            index = 0;//go to the beginning
        }else{
            index++;//otherwise add 1
        }
        
        //set the text and position
        txtNotes.setText("" + nList.get(index));
        txtNotes.setCaretPosition(0);
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        if(index == 0){//if at the beginning
            index = nList.size() - 1;//go to the end
        }else{
            index--;//otherwise remove one
        }
        
        txtNotes.setText("" + nList.get(index));
        txtNotes.setCaretPosition(0);
    }//GEN-LAST:event_btnPrevActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtNotes;
    // End of variables declaration//GEN-END:variables
}
